#!/bin/bash

# STECHX FINAL DEPLOYMENT CHECKLIST

echo "🚀 STECHX DEPLOYMENT CHECKLIST"
echo "======================================"
echo ""
echo "✅ What's Ready:"
echo "   • Frontend (Next.js 16) - Mobile responsive"
echo "   • Backend API (Express.js) - All routes configured"
echo "   • Database (PostgreSQL) - Schema ready"
echo "   • Google OAuth - Credentials configured"
echo "   • Environment variables - All set"
echo ""
echo "📋 What You Need:"
echo "   ☐ GitHub account (https://github.com/satiksh/stechx)"
echo "   ☐ Render account (https://render.com)"
echo "   ☐ Vercel account (https://vercel.com)"
echo ""
echo "⚡ Quick Start:"
echo ""
echo "STEP 1: PUSH TO GITHUB"
echo "-------"
echo "cd /Users/satikshpatel/stechx"
echo "git add ."
echo 'git commit -m "Deploy: Production-ready StechX"'
echo "git push origin main"
echo ""
echo "Then verify at: https://github.com/satiksh/stechx"
echo ""
echo "STEP 2: DEPLOY BACKEND ON RENDER"
echo "-------"
echo "1. Go to: https://render.com"
echo "2. New Web Service → Connect GitHub → satiksh/stechx"
echo "3. Configure:"
echo "   • Name: stechx-api"
echo "   • Root: api"
echo "   • Build: npm run build || true"
echo "   • Start: npm start"
echo "4. Add ALL Environment Variables (see QUICK_DEPLOY_GUIDE.md)"
echo "5. Click Deploy → Wait 5-10 min"
echo ""
echo "STEP 3: DEPLOY FRONTEND ON VERCEL"
echo "-------"
echo "1. Go to: https://vercel.com"
echo "2. New Project → Import Git → satiksh/stechx"
echo "3. IMPORTANT: Root Directory = web (dropdown)"
echo "4. Add Environment Variables:"
echo "   • NEXT_PUBLIC_API_BASE_URL = https://stechx-api.onrender.com"
echo "   • NEXT_PUBLIC_GOOGLE_CLIENT_ID = 446798573358..."
echo "5. Click Deploy → Wait 3-5 min"
echo ""
echo "STEP 4: UPDATE GOOGLE OAUTH"
echo "-------"
echo "https://console.cloud.google.com"
echo "Add authorized URLs for both Vercel and Render"
echo ""
echo "STEP 5: TEST"
echo "-------"
echo "Visit: https://stechx.vercel.app"
echo ""
echo "======================================"
echo "📚 DETAILED GUIDES:"
echo ""
echo "• FULL_DEPLOYMENT_GUIDE.md (Complete with explanations)"
echo "• QUICK_DEPLOY_GUIDE.md (Copy-paste commands)"
echo "• DEPLOY_TO_GITHUB_AND_VERCEL.sh (Automated script)"
echo ""
echo "✅ Total Time: ~25-30 minutes"
echo "======================================"
